### ISSUE TITLE
Upgrading at install time via the checkmark to NC26 still blows everything up (Windows Docker Desktop)

### ISSUE THREAD

**Issue by FlattusBlastus** [nextcloud/all-in-one#2258]
### Steps to reproduce
Step 1: Starting from nothing - Create your volumes and folders. In an administrative command box, execute:
```console
docker volume create ^
--driver local ^
--name nextcloud_aio_nextcloud_datadir ^
-o device="/d/dockerdata/nextcloud" ^
-o type="none" ^
-o o="bind"
```
```console
docker volume create ^
--driver local ^
--name nextcloud_aio_backupdir ^
-o device="/d/dockerbackup" ^
-o type="none" ^
-o o="bind"
```
Step 2. Navigate to the root of the d drive. Execute the following from the d:\ prompt: "docker compose up -d" where the following is your docker-compose.yml file:
```yaml
version: '3.9'
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /dockerdata/ncmc
  nextcloud_aio_nextcloud_datadir:
    name: nextcloud_aio_nextcloud_datadir
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /dockerdata/nextcloud
  nextcloud_aio_backupdir:
    name: nextcloud_aio_backupdir
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /dockerbackup
networks:
  nextcloud-aio:
    name: nextcloud-aio
services:
  nextcloud:
    image: nextcloud/all-in-one:beta
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - //var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=nextcloud_aio_nextcloud_datadir
      - SKIP_DOMAIN_VALIDATION=true
      - NEXTCLOUD_MEMORY_LIMIT=512M
      - NEXTCLOUD_ADDITIONAL_APKS=imagemagick aria2 yt-dlp ocrmypdf tesseract-ocr-data-deu sane-utils
      - NEXTCLOUD_STARTUP_APPS=twofactor_totp user_usage_report libresign quota_warning deck files_scripts calendar_resource_management calendar_news gestion files_lock memories notes files_zip calendar cloud_py_api group_default_quota notify_push timemanager files_archive camerarawpreviews files_accesscontrol richdocuments recognize tasks user_migration files_notify_redis groupfolders groupquota analytics dicomviewer previewgenerator workflow_script files_mindmap carnet login_notes emlviewer ransomware_protection files_linkeditor files_automatedtagging external side_menu contacts mediadc externalportal integration_youtube files_downloadactivity tvshownamer approval forms sharerenamer geoblocker integration_onedrive files_antivirus files_confidential mail collectives phonetrack files_fulltextsearch music sociallogin appointments cospend fulltextsearch_elasticsearch maps google_synchronization keeweb cadviewer tables event_update_notification ncdownloader flow_notifications files_photospheres announcementcenter fulltextsearch bookmarks unsplash files_bpm registration polls workspace files_fulltextsearch_tesseract metadata workflow_pdf_converter workflow_ocr breezedark webhooks
      - TZ=America/Los_Angeles
      - AUTOMATIC_UPDATES=1
      - DAILY_BACKUP=1
      - NEXTCLOUD_MOUNT=/e
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick inotify sysvsem
    networks:
      - nextcloud-aio
```
Step 3: Open AIO with port 8080 as usual
Step 4: Check the Upgrade to NC 26 checkbox
Step 5: BOOM

### Expected behavior
A clean install should be created. 

### Actual behavior
The following errors:
```console
2023-04-01 18:46:14 [ ] Move new files in place ...PHP Warning:  rmdir(/mnt/ncdata/updater-ocmlis599t0q/downloads/nextcloud/3rdparty/aws/aws-sdk-php/src/data): Directory not empty in phar:///var/www/html/updater/updater.phar/lib/Updater.php on line 942
[✘] Move new files in place failed
2023-04-01 18:46:14 Could not rmdir /mnt/ncdata/updater-ocmlis599t0q/downloads/nextcloud/3rdparty/aws/aws-sdk-php/src/data
2023-04-01 18:46:14 
2023-04-01 18:46:14 Update failed. To resume or retry just execute the updater again.
2023-04-01 18:46:14 Could not open input file: /var/www/html/occ
2023-04-01 18:46:14 Could not open input file: /var/www/html/occ
2023-04-01 18:46:14 Installation of Nextcloud failed!
2023-04-01 18:46:14 Could not open input file: /var/www/html/occ
2023-04-01 18:46:21 Could not open input file: /var/www/html/occ
2023-04-01 18:46:21 Waiting 10s before activating FTS...
2023-04-01 18:46:31 Activating fulltextsearch...
2023-04-01 18:46:31 Could not open input file: /var/www/html/occ
2023-04-01 18:46:31 Fulltextsearch failed. Could not index.
2023-04-01 18:46:31 Feel free to follow https://github.com/nextcloud/all-in-one/discussions/1709 if you want to skip the indexing in the future.
2023-04-01 18:46:33 [01-Apr-2023 18:46:33] NOTICE: fpm is running, pid 4161
2023-04-01 18:46:33 [01-Apr-2023 18:46:33] NOTICE: ready to handle connections
2023-04-01 18:46:33 Could not open input file: /var/www/html/cron.php
2023-04-01 18:46:43 Activating collabora config...
2023-04-01 18:46:43 Could not open input file: /var/www/html/occ
2023-04-01 18:51:33 Could not open input file: /var/www/html/cron.php
```
### Host OS
Windows 11 Home running latest Docker Desktop, WSL2, and kernel.

#### Nextcloud AIO version 
4.8 (25.0.5.1) to NC26
#### Current channel
beta
#### Other valuable info 
Apparent fix:
Added these to docker-compose.yml
environment:
```yaml
- PUID=1000
- PGID=1000
```

**Comment by FlattusBlastus** [comment]
Recommend hiding the upgrade checkmark for now and also to strongly inform people NOT to upgrade.

**Comment by FlattusBlastus** [comment]
Step 1:
docker volume create ^
--driver local ^
--name nextcloud_aio_nextcloud_datadir ^
-o device="/d/dockerdata/nextcloud" ^
-o type="none" ^
-o o="bind"

docker volume create ^
--driver local ^
--name nextcloud_aio_backupdir ^
-o device="/d/dockerbackup" ^
-o type="none" ^
-o o="bind"
Step 2:
version: '3.9'
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /dockerdata/ncmc
  nextcloud_aio_nextcloud_datadir:
    name: nextcloud_aio_nextcloud_datadir
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /dockerdata/nextcloud
  nextcloud_aio_backupdir:
    name: nextcloud_aio_backupdir
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /dockerbackup
networks:
  nextcloud-aio:
    name: nextcloud-aio
services:
  nextcloud:
    image: nextcloud/all-in-one:beta
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - //var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=nextcloud_aio_nextcloud_datadir
      - SKIP_DOMAIN_VALIDATION=true
      - NEXTCLOUD_MEMORY_LIMIT=512M
      - NEXTCLOUD_ADDITIONAL_APKS=imagemagick aria2 yt-dlp ocrmypdf tesseract-ocr-data-deu sane-utils
      - NEXTCLOUD_STARTUP_APPS=twofactor_totp user_usage_report libresign quota_warning deck files_scripts calendar_resource_management calendar_news gestion files_lock memories notes files_zip calendar cloud_py_api group_default_quota notify_push timemanager files_archive camerarawpreviews files_accesscontrol richdocuments recognize tasks user_migration files_notify_redis groupfolders groupquota analytics dicomviewer previewgenerator workflow_script files_mindmap carnet login_notes emlviewer ransomware_protection files_linkeditor files_automatedtagging external side_menu contacts mediadc externalportal integration_youtube files_downloadactivity tvshownamer approval forms sharerenamer geoblocker integration_onedrive files_antivirus files_confidential mail collectives phonetrack files_fulltextsearch music sociallogin appointments cospend fulltextsearch_elasticsearch maps google_synchronization keeweb cadviewer tables event_update_notification ncdownloader flow_notifications files_photospheres announcementcenter fulltextsearch bookmarks unsplash files_bpm registration polls workspace files_fulltextsearch_tesseract metadata workflow_pdf_converter workflow_ocr breezedark webhooks
      - TZ=America/Los_Angeles
      - AUTOMATIC_UPDATES=1
      - NEXTCLOUD_MOUNT=/e
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick inotify sysvsem
    networks:
      - nextcloud-aio
#you must save and execute this docker-compose.yml in the root of the drive you want the mastercontainer data to live in order for the folder to be created such as d: to make d:/dockerdata/ncmc automatically. You must create your backup folder (d:/dockerbackup) nextcloud data (d:/dockerdata/nextcloud) folders before running compose.
Step 3: Open AIO with port 8080 as usual
Step 4: Check the Upgrade to NC 26 checkbox
Step 5: BOOM

**Comment by FlattusBlastus** [comment]
Added these to docker-compose.yml
    environment:
      - PUID=1000
      - PGID=1000

**Comment by FlattusBlastus** [comment]
Tons of apps dont work: timemanager, Archive Manager, Calendar Newsletter, DICOM Viewer, Mind Map, Carnet, Login notes, EML Viewer, Ransomware protection, Link editor, TV Show Namer, GeoBlocker, Full text search - Files, Full text search - Elasticsearch Platform, CADViewer, NCDownloader, Full text search, Workspace, Full text search - Files - Tesseract OCR, Breeze dark, Webhooks

I know FTS will be implemented here shortly.  The other one here that I consider core functionality is Login notes. Explicit instructions of how to create an accounts is critical.

**Comment by FlattusBlastus** [comment]
This has been trashing every NC26 upgrade attempt since I started them:

2023-04-01 18:46:14 [ ] Move new files in place ...PHP Warning: rmdir(/mnt/ncdata/updater-ocmlis599t0q/downloads/nextcloud/3rdparty/aws/aws-sdk-php/src/data): Directory not empty in phar:///var/www/html/updater/updater.phar/lib/Updater.php on line 942
[✘] Move new files in place failed
2023-04-01 18:46:14 Could not rmdir /mnt/ncdata/updater-ocmlis599t0q/downloads/nextcloud/3rdparty/aws/aws-sdk-php/src/data

**Comment by Zoey2936** [comment]
> Added these to docker-compose.yml environment: - PUID=1000 - PGID=1000 The install now works. Not sure if this is ok for security?

These do nothing

**Comment by Zoey2936** [comment]
And could you pleasefill out the issue template?

**Comment by Zoey2936** [comment]
> Tons of apps dont work: timemanager, Archive Manager, Calendar Newsletter, DICOM Viewer, Mind Map, Carnet, Login notes, EML Viewer, Ransomware protection, Link editor, TV Show Namer, GeoBlocker, Full text search - Files, Full text search - Elasticsearch Platform, CADViewer, NCDownloader, Full text search, Workspace, Full text search - Files - Tesseract OCR, Breeze dark, Webhooks
> 
> I know FTS will be implemented here shortly. The other one here that I consider core functionality is Login notes. Explicit instructions of how to create an accounts is critical.

These apps are not compatible with nc 26... thats not a problem of AIO directly, you can report this to the apps directly

**Comment by FlattusBlastus** [comment]
> And could you pleasefill out the issue template?

Re-written the post

**Comment by FlattusBlastus** [comment]
If y'all don't have a Windows Docker Desktop QA tester.... I suppose I could contribute

**Comment by FlattusBlastus** [comment]
> > Added these to docker-compose.yml environment: - PUID=1000 - PGID=1000 The install now works. Not sure if this is ok for security?
> 
> These do nothing

Coincidence?

**Comment by szaimen** [comment]
This is now fixed with v4.8.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by FlattusBlastus** [comment]
Tested. Successful with issues. FTS still unable to enable at install time. Post install enable seems to work. Will test this afternoon. Recommend hard removal of FTS-Bookmarks.
