### ISSUE TITLE
Database won't start using nextcloud AIO Helm chart on Kubernetes

### ISSUE THREAD

**Issue by NGAJean** [nextcloud/all-in-one#2466]
### Steps to reproduce
1. Install Helm chart 
2. Wait 

### Expected behavior 
And after a while, everything should be set up.

### Actual behavior 
nextcloud-aio-database-cc7dcf6cf-h9ltj     0/1     CrashLoopBackOff   5 (43s ago)   4m53s

### Host OS 
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

#### Nextcloud AIO version 
Same behavior with 4.9.0 & 5.0.0 Helm chart version

**Comment by szaimen** [comment]
Hi, can you post the whole container logs here?

**Comment by NGAJean** [comment]
Only logs available from this pods are the following:
`+ rm -rf /var/lib/postgresql/data/lost+found`
After that container are restarted in loop

**Comment by szaimen** [comment]
Hm... I cannot reproduce this. Can you try to clean everything and install it again? Did you also make sure to at least add all the variables marked with todo in the variables.json?

**Comment by szaimen** [comment]
> By variables.json you mean values.yaml related to Helm chart settings, right ?

Yes

> It seams that the command are blocked here or takes too long time

Yes I see that but it makes no sense.

**Comment by NGAJean** [comment]
It's a normal behavior to me:
- each Unix system filesystems have this folder
- as it's a dedicated persistent volume this folder is expected

**Comment by szaimen** [comment]
All right! So I guess we would need to run chown -R then in this specific case?

**Comment by NGAJean** [comment]
Probably something quite similar to this https://github.com/helm/charts/issues/405

**Comment by szaimen** [comment]
What would happen if we remove this lost+found folder?

**Comment by NGAJean** [comment]
Fix should be similar to this : https://github.com/helm/charts/pull/416/commits/ccdb6e742b6c794432a73bd13e4050d3fd654d08

**Comment by szaimen** [comment]
> What would happen if we remove this lost+found folder?

Can you please answer that question?

**Comment by szaimen** [comment]
Based on https://askubuntu.com/questions/165614/is-it-safe-to-delete-a-lostfound-folder it will probably get recreated via fsck

**Comment by szaimen** [comment]
So... great!

**Comment by NGAJean** [comment]
> So... great!

I really suggest you to leave the filesystem structure clean to avoid unexpected behavior and change your kubernetes deployment to use subPath setting

**Comment by szaimen** [comment]
> I really suggest you to leave the filesystem structure clean to avoid unexpected behavior and change your kubernetes deployment to use subPath setting

yes I see what I can do.

**Comment by NGAJean** [comment]
> The problem is now that if we change this setting suddenly, it will break for exising instances IIRC...

This is another problem

**Comment by NGAJean** [comment]
> yes I see what I can do.
Let me know if you need more details or support to fix this issue

**Comment by szaimen** [comment]
> The problem is now that if we change this setting suddenly, it will break for exising instances IIRC...

Actually after thinking about it, we have some logic in place that covers this for existing instances.

**Comment by szaimen** [comment]
Should be fixed with https://github.com/nextcloud/all-in-one/pull/2467 in the next release of the helm chart.

**Comment by NGAJean** [comment]
Unfortunately your change doesn't fix the issue. I have manually try it on my side and the error is different but still doesn't work.

To be able to fix the issue, I have to do the following changes:
- Mount the volume outside of postgresql workdir:
`            - name: nextcloud-aio-database
              mountPath: /data`
- Add an additional environment variable to define the new folder to store data:
`
          env:
            - name: PGDATA
              value: /data/pgdata`

**Comment by szaimen** [comment]
The real fix is here: https://github.com/nextcloud/all-in-one/pull/2469/commits/dd5a23aaacbaa62e177cb0623752a34c0f607e5f did you try that already?

**Comment by NGAJean** [comment]
> The real fix is here: [dd5a23a](https://github.com/nextcloud/all-in-one/commit/dd5a23aaacbaa62e177cb0623752a34c0f607e5f) did you try that already?

Yes, the result is the following:
- Initial startup:
`
+ rm -rf '/var/lib/postgresql/data/*'
+ touch /mnt/data/initial-cleanup-done
+ set +ex
Setting max connections...
sed: /var/lib/postgresql/data/postgresql.conf: No such file or directory
chmod: /var/lib/postgresql/data: Operation not permitted
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
The default text search configuration will be set to "english".

Data page checksums are disabled.

pg_dump: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
pg_ctl: directory "/var/lib/postgresql/data" is not a database cluster directory
fixing permissions on existing directory /var/lib/postgresql/data ... Database dump unsuccessful!
`
- After container crashloopoin with this output:
`
Unable to restore the database because the database dump is missing.
`

**Comment by szaimen** [comment]
I see. So am I correct that the given subpath is not created automatically? That would mean that we would need to create it first, and run the chown afterwards which should fix it, correct?

**Comment by szaimen** [comment]
After thinking about this, I guess it makes sense that it is not automatically created.

**Comment by NGAJean** [comment]
> I see. So am I correct that the given subpath is not created automatically? That would mean that we would need to create it first, and run the chown afterwards which should fix it, correct?

I'm not sure to understand what you are talking about.

Maybe to clarify
 - mountPath: specify where to mount the volume **inside** the container
 - subPath: specify which path **on the volume** will be mounted (root path / by default is not defined)

Previous settings : path / on persistent volume mounted to /var/lib/postgresql/data on the container
New settings : path /data on persistent volume mounted to /var/lib/postgresql/data on the container

**Comment by szaimen** [comment]
> Maybe to clarify
> 
> * mountPath: specify where to mount the volume **inside** the container
> * subPath: specify which path **on the volume** will be mounted (root path / by default is not defined)
> 
> Previous settings : path / on persistent volume mounted to /var/lib/postgresql/data on the container New settings : path /data on persistent volume mounted to /var/lib/postgresql/data on the container

Yes, I understand. I guess I did not understand at first that the subpath folder obviously needs to get created during initcontainer in order to apply the correct permission to it.

**Comment by szaimen** [comment]
Can you check if this makes it work for you? https://github.com/nextcloud/all-in-one/pull/2480/commits/e237e2e53d82690bc75b8c0c2fff3dadb3bfa614

**Comment by szaimen** [comment]
So I guess we need to use sh -c then... 🙈

**Comment by NGAJean** [comment]
> So I guess we need to use sh -c then... 🙈

With 2 different init containers it works 🙈

**Comment by szaimen** [comment]
> > So I guess we need to use sh -c then... 🙈
> 
> With 2 different init containers it works 🙈

I thought so! Kubernetes is sometimes so awkward! 🙈

**Comment by szaimen** [comment]
This should now be fixed with https://github.com/nextcloud/all-in-one/releases/tag/helm-chart-5.1.0
