### ISSUE TITLE
New preview images / thumbs (of large photos) are black & white only

### ISSUE THREAD

**Issue by kce68** [nextcloud/all-in-one#4239]
### Steps to reproduce
1. Make a fresh Install; but it happens also after updating: In my case from AiO 7.9.1 to 7.12.1
2. Open Photos-folder in Files
3. Take a Look at the standard "nextcloud group photo" / upload a new colored Photo 
4. Click on it: It's in B&W
5. Click the editing pencil: Photo becomes colored
6. Edit something and save it as new Photo: Previews und thumbnails ar generate in B&W

### Expected behavior 
Colored should be colored `:)`
As ist it works in all my installation with AiO 7.9.1

### Actual behavior 
Thumbnails and Previews are generated in B&W, when JPEG or PNGs have 12 megapixels
I found out that only smaller Photos seem to work. I checked PNG and JPEG.

Any ideas? Let me know if you need more information.

### Host OS 
KVM-VM in Proxmox with Ubuntu 22.4 LTS all updates as of today
has 6 GB RAM and 4 CPUs
Docker from the Docker apt-repositories
Deployed with docker compose via a Portainer EE
Behind a HAproxy

#### Nextcloud AIO version 
7.9.1 working and 7.12.1 not working
regardless of updating, fresh install with NC 27 or NC 28
with Containers:
 Apache ([Running]
 Database ([Running]
 Nextcloud ([Running]
 Notify Push ([Running]
 Redis ([Running]
 Collabora ([Running]
 Talk ([Running]
 Imaginary ([Running]
 Fulltextsearch ([Running]

#### Current channel 
Latest

#### Other valuable info 

My docker-compose:
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      - 8080:8080
    #  - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      - NEXTCLOUD_DATADIR=/smb/nxcdata # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      - NEXTCLOUD_UPLOAD_LIMIT=20G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      - NEXTCLOUD_MAX_TIME=7200 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      - TALK_PORT=30678 # This allows to adjust the port that the talk container is using.
```

My haproxy.conf :
```
# Automaticaly generated, dont edit manually.
# Generated on: 2024-02-17 09:34
global
	maxconn			15000
	stats socket /tmp/haproxy.socket level admin  expose-fd listeners
	uid			80
	gid			80
	nbproc			1
	nbthread			1
	hard-stop-after		15m
	chroot				/tmp/haproxy_chroot
	daemon
	tune.ssl.default-dh-param	2048
	server-state-file /tmp/haproxy_server_state

listen HAProxyLocalStats
	bind 127.0.0.1:2200 name localstats
	mode http
	stats enable
	stats refresh 5
	stats admin if TRUE
	stats show-legends
	stats uri /haproxy/haproxy_stats.php?haproxystats=1
	timeout client 5000
	timeout connect 5000
	timeout server 5000

frontend Nextcloud-INGRES
	bind			136.243.179.76:443 name 136.243.179.76:443   ssl crt-list /var/etc/haproxy/Nextcloud-INGRES.crt_list  
	mode			http
	log			global
	option			http-keep-alive
	option			forwardfor
	acl https ssl_fc
	http-request set-header		X-Forwarded-Proto http if !https
	http-request set-header		X-Forwarded-Proto https if https
	maxconn			8000
	timeout client		30000
	acl			test-acl	var(txn.txnhost) -m sub -i nxctest.bindix
	acl			aclcrt_Nextcloud-INGRES	var(txn.txnhost) -m reg -i ^nxctest\.bindix\.de(:([0-9]){1,5})?$
	http-request set-var(txn.txnhost) hdr(host)
	use_backend nxc-test-BE_ipvANY  if  test-acl aclcrt_Nextcloud-INGRES

backend nxc-test-BE_ipvANY
	mode			http
	id			107
	log			global
	timeout connect		300000
	timeout server		300000
	retries			3
	option			httpchk OPTIONS / 
	server			NXC-test-Dienst 192.168.130.36:11000 id 101 check inter 1000
```

One of my Example Photo 2 reproduce :)

![IMG_9782](https://github.com/nextcloud/all-in-one/assets/77016734/02b3c4e0-bd3f-404a-9963-1cf83f93dbe8)

**Comment by martin-nohava** [comment]
Can confirm, I have the same issue after update to 7.12.1.

**Comment by szaimen** [comment]
Hi, I fear I cannot reproduce your issue :/

![image](https://github.com/nextcloud/all-in-one/assets/42591237/53d312d8-4232-4933-96e4-d315df7a73f4)

**Comment by szaimen** [comment]
But the picture you've sent is also only 6.3MB big... maybe that is the reason? Do you have one example file for me with 12MB as outlined?

**Comment by kce68** [comment]
> But the picture you've sent is also only 6.3MB big... maybe that is the reason? Do you have one example file for me with 12MB as outlined?

Well, I ment 12 MegaPixel  (3000x4000 Pixels).

I can send you an eMail with credentials, if you are interested to investigate in my enviroment. It is a separated VM with no private data on it.

**Comment by vposloncec** [comment]
For me it happens for all image previews that were created since the update. I'm running nextcloud-aio in a proxmox VM. for setup, I've followed reverse-proxy cloudflare tunnel guide (running with docker run command).

**Comment by kce68** [comment]
> Can confirm, I have the same issue after update to 7.12.1.

Thanks, ... Im happy not to be alone with that issue. Now it's about to find out for the reasons.

**Comment by PfannenHans** [comment]
The issue is the imaginary container as just tried to set it up with the standalone nextcloud docker image and i got the same behaviour. Can also be tested  using `curl -O "http://$IMAGINARY-IP:9000/crop?width=500&height=400&url=https://raw.githubusercontent.com/h2non/imaginary/master/testdata/large.jpg"`  
Using the older "20240201_120631-latest"-Tag for the container instead of the latest also resolves the issue, so there is a regression somewhere.

**Comment by jan315** [comment]
Same problem, happed with all new heic uploads since update.

**Comment by szaimen** [comment]
I fear I can still not reproduce this. Can you maybe post the imaginary container logs and nextcloud logs here?

**Comment by kce68** [comment]
Hi Simon, here we are ... :)

[logs-as-requested.txt](https://github.com/nextcloud/all-in-one/files/14328345/logs-as-requested.txt)

**Comment by szaimen** [comment]
Hm, the logs do not show anything useful :/

Can you also share the logs that are avaialble via `https://yourdomain.com/settings/admin/logging` ?

**Comment by kce68** [comment]
@szaimen  Your help is really wellcome ! Here's the log. But I fear this log is also quite boring ...
[nextcloud.log](https://github.com/nextcloud/all-in-one/files/14330748/nextcloud.log)
Want to come on the machine to investigate any further?

**Comment by rodonile** [comment]
Hi all, just wanted to share I am experiencing the same issue

**Comment by fireblade2534** [comment]
Same issue here

**Comment by CyberCowboy** [comment]
For what it's worth, I'm having the same issue, rebuilt AIO and still happening.

**Comment by jan315** [comment]
My temporary fix was to change master container version to previous release '20240201_120631-latest' and move affected files to PC then back to NC to be correctly displayed.

**Comment by c0urier** [comment]
> 20240201_120631-latest

I can confirm that downgrading to 20240201_120631-latest solved the problem for me to. Thank you!

**Comment by corincorvus** [comment]
Cant go back to mastercontainer 20240201_120631-latest

I get this error, if i do this. If i dont restart the Containers with the 20240201_120631-latest Mastercontainer, in my case the problem persists.


```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 109
Initial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080
If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443
++ head -1 /mnt/docker-aio-config/data/daily_backup_time
+ BACKUP_TIME=01:00
+ export BACKUP_TIME
+ export DAILY_BACKUP=1
+ DAILY_BACKUP=1
++ sed -n 2p /mnt/docker-aio-config/data/daily_backup_time
+ '[' '' '!=' automaticUpdatesAreNotEnabled ']'
+ export AUTOMATIC_UPDATES=1
+ AUTOMATIC_UPDATES=1
++ sed -n 3p /mnt/docker-aio-config/data/daily_backup_time
+ '[' '' '!=' successNotificationsAreNotEnabled ']'
+ export SEND_SUCCESS_NOTIFICATIONS=1
+ SEND_SUCCESS_NOTIFICATIONS=1
+ set +x
INF INF INF INF INF INF INF INF ts=1708418528.4070334 INF INF INF INF INF INF INF INF ts=1708418528.4070334 msg=using provided configuration INF INF INF INF INF INF INF INF ts=1708418528.4070334 INF INF INF INF INF INF INF INF ts=1708418528.4070334 msg=using provided configuration config_file=/Caddyfile INF INF INF INF INF INF INF INF ts=1708418528.4070334 INF INF INF INF INF INF INF INF ts=1708418528.4070334 msg=using provided configuration INF INF INF INF INF INF INF INF ts=1708418528.4070334 INF INF INF INF INF INF INF INF ts=1708418528.4070334 msg=using provided configuration config_file=/Caddyfile config_adapter=
[20-Feb-2024 08:42:08] NOTICE: fpm is running, pid 137
[20-Feb-2024 08:42:08] NOTICE: ready to handle connections
[Tue Feb 20 08:42:08.494462 2024] [mpm_event:notice] [pid 131:tid 140397545249608] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.4 configured -- resuming normal operations
[Tue Feb 20 08:42:08.495295 2024] [core:notice] [pid 131:tid 140397545249608] AH00094: Command line: 'httpd -D FOREGROUND'
Deleting duplicate sessions
NOTICE: PHP message: Slim Application Error
Type: Exception
Code: 0
Message: Could not pull image nextcloud/aio-postgresql:20240201_120631-latest. Please run &#039;sudo docker exec -it nextcloud-aio-mastercontainer docker pull nextcloud/aio-postgresql:20240201_120631-latest&#039; in order to find out why it failed.
File: /var/www/docker-aio/php/src/Docker/DockerActionManager.php

2
Trace: #0 /var/www/docker-aio/php/src/Controller/DockerController.php(54): AIO\Docker\DockerActionManager->PullImage(Object(AIO\Container\Container))
#1 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-d...', true)
#2 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-n...', true)
#3 /var/www/docker-aio/php/src/Controller/DockerController.php(202): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-a...', true)
#4 /var/www/docker-aio/php/src/Controller/DockerController.php(182): AIO\Controller\DockerController->startTopContainer(true)
#5 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): AIO\Controller\DockerController->StartContainer(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#12 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#13 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#14 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#15 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#16 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#17 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#19 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#20 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#21 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#22 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
#23 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
```

**Comment by szaimen** [comment]
Hi, can some of you for a test switch to `20240215_092413-latest` and check if that works as well?

**Comment by corincorvus** [comment]
> Hi, can some of you for a test switch to `20240215_092413-latest` and check if that works as well?

On this Version the Error is back
![image](https://github.com/nextcloud/all-in-one/assets/21257329/02f174fa-3845-4031-a90d-2d762bbe0173)
![image](https://github.com/nextcloud/all-in-one/assets/21257329/c8631401-d802-4b35-b280-ad2bf0bc02a5)

**Comment by szaimen** [comment]
I see. Can you run 
```
sudo docker stop nextcloud-aio-imaginary
sudo docker rm nextcloud-aio-imaginary
sudo docker image prune -a
```
And then open the aio interface again and stop and start the containers again and check if that resolves things?

**Comment by corincorvus** [comment]
At the Moment i cant test with newer Version. 
My Instance is productive and i only have time slots in the morning and between 15-17 o clock.

**Comment by jeantoulza** [comment]
> Downgrade worked now, (image conflict) solved the problem. Thanks.
> 
> Waiting for Fix
> 
> But how can i fix already uploaded files? occ preview:generate-all didnt solve it. Thanks

Just fixed it on my instance. Basically you remove all corrupted previews then rescan appdata preview folder. Removed previews will be regenerated on-the-fly when you request them (by opening the photos app for example).
```bash
DAYS=7  # replace with the number of days since the previews were corrupted
NEXTCLOUD_APPDATA=/nextcloud/appdata_randomid  # replace with your own appdata folder

# delete bad previews
find "$NEXTCLOUD_APPDATA" -ctime -$DAYS -type f -delete

# rescan preview folder in appdata
occ files:scan-app-data preview
```

Backup `$NEXTCLOUD_APPDATA` just in case before running this.

**Comment by Stunnerr** [comment]
> ```
> sudo docker stop nextcloud-aio-imaginary
> sudo docker rm nextcloud-aio-imaginary
> sudo docker image prune -a
> ```

Tried this, did not help with old nor new ones.

**Comment by CyberCowboy** [comment]
> I see. For everyone, can you run
> 
> ```
> sudo docker stop nextcloud-aio-imaginary
> sudo docker rm nextcloud-aio-imaginary
> sudo docker image prune -a
> ```
> 
> And then open the aio interface again and stop and start the containers again and check if that resolves things?

No good for me, using AIO v7.12.1

**Comment by usngrimsley** [comment]
> I see. For everyone, can you run 
> 
> ```
> 
> sudo docker stop nextcloud-aio-imaginary
> 
> sudo docker rm nextcloud-aio-imaginary
> 
> sudo docker image prune -a
> 
> ```
> 
> And then open the aio interface again and stop and start the containers again and check if that resolves things?

No go as well

**Comment by jonny-379** [comment]
I have the same problem on my AIO v7.21.1...

> I see. For everyone, can you run
> 
> ```
> sudo docker stop nextcloud-aio-imaginary
> sudo docker rm nextcloud-aio-imaginary
> sudo docker image prune -a
> ```
> 
> And then open the aio interface again and stop and start the containers again and check if that resolves things?

Well it works kinda, when I stop and remove it, previews have colour again (when opening the images shown in nextcloud in a new tab (right click) the image is called preview).
But when I then stop & start the docker in the AIO admin interface the problem comes back.

So I'll stop and remove it, and just run like that.

**Comment by szaimen** [comment]
Hi, I just released a fix with v7.13.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

See how to remove broken previews: https://github.com/nextcloud/all-in-one/issues/4239#issuecomment-1954971592

**Comment by CyberCowboy** [comment]
> 1. First, open the aio interface and create a backup and start your containers again after the backup is successful.
> 2. Afterwards, run via CLI:
> 
> ```
> # Go into the container
> sudo docker exec --user www-data -it nextcloud-aio-nextcloud bash
> ```
> 
> 3. Now inside the container:
> 
> ```
> DAYS=7  # replace with the number of days since the previews were corrupted (earliest was 8th february)
> 
> # delete bad previews
> find "/mnt/ncdata/appdata_*/preview" -ctime -$DAYS -type f -delete
> 
> # rescan preview folder in appdata
> php occ files:scan-app-data preview
> ```

I'm putting the above command (with modification for app_* and replacing days with 70) in a file called ncimagefix then chmod +x

When I run it I"m getting
` ./ncimagefix
Could not open input file: occ
`

if I try to sudo while in the bash instance it asks for www-data password which I don't know/have.


I'm fairly new to NC, having started it about 2 weeks ago, so this problem has really been a hassle as I thought I was doing something wrong.

**Comment by CyberCowboy** [comment]
BTW I did update to the Beta, so am trying to see if that fixed the issue

**Comment by CyberCowboy** [comment]
I modified the suggested way to regenerate previews, and I think it runs correctly, but if so no change.

I'm running from the docker host with this code:

`DAYS=70  # replace with the number of days since the previews were corrupted
NEXTCLOUD_APPDATA=/mnt/storage/appdata_oc73brnah5op #replace with your own appdata folder

# delete bad previews
find "$NEXTCLOUD_APPDATA/preview" -ctime -$DAYS -type f -delete

# rescan preview folder in appdata
 docker exec --user www-data -it nextcloud-aio-nextcloud php occ files:scan-app-data preview
`

Can anyone confirm if that should work?  As I said, if so with 7.13.0 beta it doesn't seem to change.

**Comment by usngrimsley** [comment]
Updated to v7.13.0 beta. Uploaded several pictures and looks to have fixed the issue with new upload. (Apple iOS 17.2.1 / App version 5.0.1.0 and 5.1)

**Comment by m4nges** [comment]
> Hi, I just released a fix with v7.13.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
> 
> ⚠️ See how to remove broken previews: [#4239 (comment)](https://github.com/nextcloud/all-in-one/issues/4239#issuecomment-1954971592)

This worked like charme!

**Comment by zvarnes** [comment]
Beta update worked for me. Thanks for the quick fix 🫂

**Comment by matteoipri** [comment]
I did not experience the issue before, but I switched my all-in-one test instance to the beta channel and the previews are generate correctly for iPhone taken photos.

PS: I am waiting to have the nextcloud/docker [28.0.2] and nextcloud/all-in-one [28.0.1] on the same version to do a migration, mostly for these previews missing with my current deployment.

**Comment by jonny-379** [comment]
> Hi, I just released a fix with v7.13.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
> 
> ⚠️ See how to remove broken previews: [#4239 (comment)](https://github.com/nextcloud/all-in-one/issues/4239#issuecomment-1954971592)

The beta fixed the problem for me to.

**Comment by corincorvus** [comment]
Beta Channel i cant use fulltextsearch and clamav container. both are only shows errors. Without it starts. Photo problem is fixed (50 testruns)

fulltextsearch cant start cause problem with db version
`exception during geoip databases update | @timestamp=2024-02-22T13:27:42.530Z log.level=ERROR ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[d45d52cf6edd][generic][T#4] log.logger=org.elasticsearch.ingest.geoip.GeoIpDownloader elasticsearch.cluster.uuid=rKwx2yHURCSG5KM3Ki17mw elasticsearch.node.id=Q7PmvilARy2_Imj_MtpsFA elasticsearch.node.name=d45d52cf6edd elasticsearch.cluster.name=nextcloud-aio error.type=org.elasticsearch.ElasticsearchException error.message=not all primary shards of [.geoip_databases] index are active error.stack_trace=org.elasticsearch.ElasticsearchException: not all primary shards of [.geoip_databases] index are active`

clamav cant find Socket
```
Starting Freshclamd
Starting ClamAV

Socket for clamd not found yet, retrying (0/90) ...ClamAV update process started at Thu Feb 22 13:24:45 2024
daily.cld database is up-to-date (version: 27193, sigs: 2053961, f-level: 90, builder: raynman)
main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
bytecode.cvd database is up-to-date (version: 334, sigs: 91, f-level: 90, builder: anvilleg)

Socket for clamd not found yet, retrying (1/90) ...
Socket for clamd not found yet, retrying (2/90) ...
Socket for clamd not found yet, retrying (3/90) ...
Socket for clamd not found yet, retrying (4/90) ...
Socket for clamd not found yet, retrying (5/90) ...
Socket for clamd not found yet, retrying (6/90) ...
Socket for clamd not found yet, retrying (7/90) ...
Socket for clamd not found yet, retrying (8/90) ...
Socket for clamd not found yet, retrying (9/90) ...
Socket for clamd not found yet, retrying (10/90) ...
Socket for clamd not found yet, retrying (11/90) ...
Socket for clamd not found yet, retrying (12/90) ...
Socket for clamd not found yet, retrying (13/90) ...
Socket for clamd not found yet, retrying (14/90) ...
Socket for clamd not found yet, retrying (15/90) ...
Socket for clamd not found yet, retrying (16/90) ...
Socket for clamd not found yet, retrying (17/90) ...
Socket for clamd not found yet, retrying (18/90) ...
Socket for clamd not found yet, retrying (19/90) ...
Socket for clamd not found yet, retrying (20/90) ...
Socket for clamd not found yet, retrying (21/90) ...
Socket for clamd not found yet, retrying (22/90) ...
Socket for clamd not found yet, retrying (23/90) ...
Socket for clamd not found yet, retrying (24/90) ...
Socket for clamd not found yet, retrying (25/90) ...
Socket for clamd not found yet, retrying (26/90) ...
Socket for clamd not found yet, retrying (27/90) ...
Socket for clamd not found yet, retrying (28/90) ...
Socket for clamd not found yet, retrying (29/90) ...
Socket for clamd not found yet, retrying (30/90) ...
Socket for clamd not found yet, retrying (31/90) ...
Socket for clamd not found yet, retrying (32/90) ...
Socket for clamd not found yet, retrying (33/90) ...
Socket for clamd not found yet, retrying (34/90) ...
Socket for clamd not found yet, retrying (35/90) ...
Socket for clamd not found yet, retrying (36/90) ...
Socket for clamd not found yet, retrying (37/90) ...
Socket for clamd not found yet, retrying (38/90) ...
Socket for clamd not found yet, retrying (39/90) ...
Socket for clamd not found yet, retrying (40/90) ...
Socket for clamd not found yet, retrying (41/90) ...
Socket for clamd not found yet, retrying (42/90) ...
Socket for clamd not found yet, retrying (43/90) ...
Socket for clamd not found yet, retrying (44/90) ...
Socket for clamd not found yet, retrying (45/90) ...
Socket for clamd not found yet, retrying (46/90) ...
Socket for clamd not found yet, retrying (47/90) ...
Socket for clamd not found yet, retrying (48/90) ...
Socket for clamd not found yet, retrying (49/90) ...
Socket for clamd not found yet, retrying (50/90) ...
Socket for clamd not found yet, retrying (51/90) ...
Socket for clamd not found yet, retrying (52/90) ...
Socket for clamd not found yet, retrying (53/90) ...
Socket for clamd not found yet, retrying (54/90) ...
Socket for clamd not found yet, retrying (55/90) ...
Socket for clamd not found yet, retrying (56/90) ...
Socket for clamd not found yet, retrying (57/90) ...
Socket for clamd not found yet, retrying (58/90) ...
Socket for clamd not found yet, retrying (59/90) ...
Socket for clamd not found yet, retrying (60/90) ...
Socket for clamd not found yet, retrying (61/90) ...
Socket for clamd not found yet, retrying (62/90) ...
Socket for clamd not found yet, retrying (63/90) ...
Socket for clamd not found yet, retrying (64/90) ...
Socket for clamd not found yet, retrying (65/90) ...
Socket for clamd not found yet, retrying (66/90) ...
Socket for clamd not found yet, retrying (67/90) ...
Socket for clamd not found yet, retrying (68/90) ...
Socket for clamd not found yet, retrying (69/90) ...
Socket for clamd not found yet, retrying (70/90) ...
Socket for clamd not found yet, retrying (71/90) ...
Socket for clamd not found yet, retrying (72/90) ...
Socket for clamd not found yet, retrying (73/90) ...
Socket for clamd not found yet, retrying (74/90) ...
Socket for clamd not found yet, retrying (75/90) ...
Socket for clamd not found yet, retrying (76/90) ...
Socket for clamd not found yet, retrying (77/90) ...
Socket for clamd not found yet, retrying (78/90) ...
Socket for clamd not found yet, retrying (79/90) ...
Socket for clamd not found yet, retrying (80/90) ...
Socket for clamd not found yet, retrying (81/90) ...
Socket for clamd not found yet, retrying (82/90) ...
Socket for clamd not found yet, retrying (83/90) ...
Socket for clamd not found yet, retrying (84/90) ...
Socket for clamd not found yet, retrying (85/90) ...
Socket for clamd not found yet, retrying (86/90) ...
Socket for clamd not found yet, retrying (87/90) ...
Socket for clamd not found yet, retrying (88/90) ...
Socket for clamd not found yet, retrying (89/90) ...
Socket for clamd not found yet, retrying (90/90) ...
Failed to start clamd
Starting Freshclamd
Starting ClamAV

Socket for clamd not found yet, retrying (0/90) ...ClamAV update process started at Thu Feb 22 13:26:24 2024
daily.cld database is up-to-date (version: 27193, sigs: 2053961, f-level: 90, builder: raynman)
main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
bytecode.cvd database is up-to-date (version: 334, sigs: 91, f-level: 90, builder: anvilleg)

```

**Comment by hmarti54** [comment]
I updated to beta and this did not fix the issue for me for photos that are already on nextcloud. Haven't tried on newly uploaded pics  but don't really want to have to re-upload a ton of photos..


> > Downgrade worked now, (image conflict) solved the problem. Thanks.
> > Waiting for Fix
> > But how can i fix already uploaded files? occ preview:generate-all didnt solve it. Thanks
> 
> Just fixed it on my instance. Basically you remove all corrupted previews then rescan appdata preview folder. Removed previews will be regenerated on-the-fly when you request them (by opening the photos app for example). You may have to delete your browser cache to see the new previews.
> 
> 1. First, open the aio interface and create a backup and start your containers again after the backup is successful.
> 2. Afterwards, run via CLI:
> 
> ```
> # Go into the container
> sudo docker exec --user www-data -it nextcloud-aio-nextcloud bash
> ```
> 
> 3. Now inside the container:
> 
> ```
> DAYS=7  # replace with the number of days since the previews were corrupted (earliest was 8th february)
> 
> # delete bad previews
> find "/mnt/ncdata/appdata_*/preview" -ctime -$DAYS -type f -delete
> 
> # rescan preview folder in appdata
> php occ files:scan-app-data preview
> ```

This isn't working for me, says no such file or directory (I have tried several options of renaming the file path to see if it works)

**Comment by szaimen** [comment]
Hi, we upgraded Alpine Linux in the Imaginary container again and released that with v9.1.0 Beta. 
Please test uploading Photos from the iOS app and check if the previews look fine. If not, please log an issue.
Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
