### ISSUE TITLE
Problems with nextcloud office since update to aio 10

### ISSUE THREAD

**Issue by 4tler** [nextcloud/all-in-one#5682]
/
### Steps to reproduce
1. create a new nextcloud office document under files
2. choose a template
3. you receive an error message ‘New file cannot be created from template’
4. if you refresh the page, the file will still be created.

### Expected behavior 

Hello, since the update to NC AIO 10 I have the problem that my log runs full as soon as I use Nc Office. There seems to be some kind of access problem. I can see this behaviour with a new instance and an old updated instance. The instances are running on different servers each behind a nginxproxymanager which is configured as recommended here.  

Everything else works fine and existing NC Office files can also be edited and saved, but I still get many entries in the log.

This error was not present before the update.

#### Host OS 

I have installed everything under Proxmox as Ubuntu 24.04 LXC.
Everything is up-to-date. 

#### Output of `sudo docker info`
<details><summary>Details</summary>
<p>
root@Nextcloud-kastl:~# sudo docker info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.12-4-pve
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 8GiB
 Name: Nextcloud_K
 ID: 44dbc800-dd64-42c7-a707-9230515e063c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

</p>
</details> 

#### Other valuable info 
nextcloud-aio-collabora log:

```shell
2024-11-30T08:00:11.563143598Z frk-00013-00013 2024-11-30 09:00:11.563037 +0100 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/hosts] is out-of-date. Will have to clone dynamic elements of systemplate to the jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:585
2024-11-30T08:00:11.579594568Z wsd-00007-00011 2024-11-30 09:00:11.579488 +0100 [ coolwsd ] WRN  Waking up dead poll thread [main], started: false, finished: false| net/Socket.hpp:810
2024-11-30T08:00:11.579633232Z wsd-00007-00007 2024-11-30 09:00:11.579551 +0100 [ coolwsd ] WRN  Waking up dead poll thread [main], started: false, finished: false| net/Socket.hpp:810
2024-11-30T08:01:51.642979858Z wsd-00007-00021 2024-11-30 09:01:51.642892 +0100 [ websrv_poll ] WRN  convert-to: Requesting address is denied: xx.xxx.xxx.xxx|| wsd/ClientRequestDispatcher.cpp:497
2024-11-30T08:01:51.845366877Z wsd-00007-00021 2024-11-30 09:01:51.845291 +0100 [ websrv_poll ] WRN  convert-to: Requesting address is denied: xx.xxx.xxx.xxx|| wsd/ClientRequestDispatcher.cpp:497
2024-11-30T08:02:02.755716587Z wsd-00007-00021 2024-11-30 09:02:02.755630 +0100 [ websrv_poll ] WRN  convert-to: Requesting address is denied: xx.xxx.xxx.xxx|| wsd/ClientRequestDispatcher.cpp:497
2024-11-30T08:02:02.821006938Z wsd-00007-00021 2024-11-30 09:02:02.820765 +0100 [ websrv_poll ] WRN  convert-to: Requesting address is denied: xx.xxx.xxx.xxx|| wsd/ClientRequestDispatcher.cpp:497
2024-11-30T08:08:26.736879761Z wsd-00007-00021 2024-11-30 09:08:26.736820 +0100 [ websrv_poll ] WRN  convert-to: Requesting address is denied: xx.xxx.xxx.xxx| wsd/ClientRequestDispatcher.cpp:440
2024-11-30T08:08:26.736921710Z wsd-00007-00021 2024-11-30 09:08:26.736834 +0100 [ websrv_poll ] WRN  #21: Conversion requests not allowed from this address: ::ffff:172.18.0.10| wsd/ClientRequestDispatcher.cpp:1509
2024-11-30T08:08:26.756895154Z wsd-00007-00021 2024-11-30 09:08:26.756841 +0100 [ websrv_poll ] WRN  convert-to: Requesting address is denied: xx.xxx.xxx.xxx| wsd/ClientRequestDispatcher.cpp:440
2024-11-30T08:08:26.756919029Z wsd-00007-00021 2024-11-30 09:08:26.756853 +0100 [ websrv_poll ] WRN  #21: Conversion requests not allowed from this address: ::ffff:172.18.0.10| wsd/ClientRequestDispatcher.cpp:1509
``` 
NC log:
```
`{
  "reqId": "OFfIQoODoglHbRXASADe",
  "level": 3,
  "time": "2024-11-30T08:08:29+00:00",
  "remoteAddr": "xx.xxx.xxx.xxx",
  "user": "admin",
  "app": "richdocuments",
  "method": "POST",
  "url": "/ocs/v2.php/apps/files/api/v1/templates/create",
  "message": "Client error: `POST https://cloud.xxx.de/cool/transform-document-structure` resulted in a `403 Forbidden` response",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "version": "30.0.2.2",
  "data": {
    "app": "richdocuments"
  },
  "id": "674acadb25bfe"
}`
```

**Comment by leonardodeglinnocenti** [comment]
I get a different error message, but it seems correlated. I post it here in case it helps:

```
[richdocuments] Error: Client error: `POST ***.net/cool/extract-document-structure?limit=content-control` resulted in a `403 Forbidden` response
GET /ocs/v2.php/apps/files/api/v1/templates
from *** by leonardo at 1 dic 2024, 11:36:37
```
NC Office seems working fine, but I'm flooded by this error message. In my case I get ```/cool/extract-document-structure?limit=content-control``` instead of ```/cool/transform-document-structure```.

DETAILS:
Version: Nextcloud AIO v10.0.0 (error appeared after the update)
Host OS: Debian 12 (Proxmox VM)
Optional containers: Collabora, Fulltextsearch, Imaginary, Nextcloud Talk, Nextcloud Talk Recording-server, Docker Socket Proxy, Whiteboard

DETAILED LOG:
```
{
  "reqId": "jpF61NGBCemPliigND3B",
  "level": 3,
  "time": "2024-12-01T10:36:37+00:00",
  "remoteAddr": "***",
  "user": "leonardo",
  "app": "richdocuments",
  "method": "GET",
  "url": "/ocs/v2.php/apps/files/api/v1/templates",
  "message": "Client error: `POST https://***.net/cool/extract-document-structure?limit=content-control` resulted in a `403 Forbidden` response",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0",
  "version": "30.0.2.2",
  "data": {
    "app": "richdocuments"
  },
  "id": "674c3e1a8ace4"
}
```

**Comment by szaimen** [comment]
This is now fixed with v10.1.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by 4tler** [comment]
I testet it but the problem is still exist

Message in LOG:

<details><summary>Details</summary>
<p>

```
{
  "reqId": "KwCoddSAVIKkefDPyhsN",
  "level": 3,
  "time": "2024-12-13T16:21:44+00:00",
  "remoteAddr": "IP",
  "user": "user",
  "app": "no app in context",
  "method": "POST",
  "url": "/ocs/v2.php/apps/files/api/v1/templates/create",
  "message": "Client error: `POST https://cloud.domain.de/cool/transform-document-structure` resulted in a `403 Forbidden` response",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "version": "30.0.4.1",
  "exception": {
    "Exception": "GuzzleHttp\\Exception\\ClientException",
    "Message": "Client error: `POST https://cloud.domain.de/cool/transform-document-structure` resulted in a `403 Forbidden` response",
    "Code": 403,
    "Trace": [
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php",
        "line": 72,
        "function": "create",
        "class": "GuzzleHttp\\Exception\\RequestException",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 209,
        "function": "GuzzleHttp\\{closure}",
        "class": "GuzzleHttp\\Middleware",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 158,
        "function": "callHandler",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "::",
        "args": [
          1,
          "*** sensitive parameters replaced ***",
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/TaskQueue.php",
        "line": 52,
        "function": "GuzzleHttp\\Promise\\{closure}",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 251,
        "function": "run",
        "class": "GuzzleHttp\\Promise\\TaskQueue",
        "type": "->",
        "args": [
          true
        ]
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 227,
        "function": "invokeWaitFn",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 272,
        "function": "waitIfPending",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 229,
        "function": "invokeWaitList",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php",
        "line": 69,
        "function": "waitIfPending",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php",
        "line": 189,
        "function": "wait",
        "class": "GuzzleHttp\\Promise\\Promise",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/Http/Client/Client.php",
        "line": 276,
        "function": "request",
        "class": "GuzzleHttp\\Client",
        "type": "->",
        "args": [
          "post",
          "*** sensitive parameters replaced ***",
          {
            "0": "And 1 more entries, set log level to debug to see all entries",
            "verify": "/var/www/html/resources/config/ca-bundle.crt",
            "timeout": 5,
            "nextcloud": {
              "allow_local_address": true
            },
            "multipart": [
              {
                "name": "data",
                "contents": null,
                "headers": {
                  "Content-Type": "multipart/form-data"
                }
              },
              {
                "name": "transform",
                "contents": "{\"Transforms\": []}"
              },
              {
                "name": "format",
                "contents": "ott"
              }
            ],
            "headers": {
              "User-Agent": "Nextcloud Server Crawler",
              "Accept-Encoding": "gzip"
            }
          }
        ]
      },
      {
        "file": "/var/www/html/custom_apps/richdocuments/lib/Service/TemplateFieldService.php",
        "line": 186,
        "function": "post",
        "class": "OC\\Http\\Client\\Client",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/richdocuments/lib/Listener/FileCreatedFromTemplateListener.php",
        "line": 61,
        "function": "fillFields",
        "class": "OCA\\Richdocuments\\Service\\TemplateFieldService",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Files\\Node\\File"
          },
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/lib/private/EventDispatcher/ServiceEventListener.php",
        "line": 68,
        "function": "handle",
        "class": "OCA\\Richdocuments\\Listener\\FileCreatedFromTemplateListener",
        "type": "->",
        "args": [
          {
            "__class__": "OCP\\Files\\Template\\FileCreatedFromTemplateEvent"
          }
        ]
      },
      {
        "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 220,
        "function": "__invoke",
        "class": "OC\\EventDispatcher\\ServiceEventListener",
        "type": "->",
        "args": [
          {
            "__class__": "OCP\\Files\\Template\\FileCreatedFromTemplateEvent"
          },
          "OCP\\Files\\Template\\FileCreatedFromTemplateEvent",
          {
            "__class__": "Symfony\\Component\\EventDispatcher\\EventDispatcher"
          }
        ]
      },
      {
        "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 56,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          [
            {
              "__class__": "Closure"
            }
          ],
          "OCP\\Files\\Template\\FileCreatedFromTemplateEvent",
          {
            "__class__": "OCP\\Files\\Template\\FileCreatedFromTemplateEvent"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 67,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCP\\Files\\Template\\FileCreatedFromTemplateEvent"
          },
          "OCP\\Files\\Template\\FileCreatedFromTemplateEvent"
        ]
      },
      {
        "file": "/var/www/html/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 79,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          "OCP\\Files\\Template\\FileCreatedFromTemplateEvent",
          {
            "__class__": "OCP\\Files\\Template\\FileCreatedFromTemplateEvent"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Template/TemplateManager.php",
        "line": 162,
        "function": "dispatchTyped",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCP\\Files\\Template\\FileCreatedFromTemplateEvent"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/files/lib/Controller/TemplateController.php",
        "line": 68,
        "function": "createFromTemplate",
        "class": "OC\\Files\\Template\\TemplateManager",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 208,
        "function": "create",
        "class": "OCA\\Files\\Controller\\TemplateController",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 114,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Files\\Controller\\TemplateController"
          },
          "create"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 161,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Files\\Controller\\TemplateController"
          },
          "create"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Files\\Controller\\TemplateController",
          "create",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "ocs.files.template.create"
          }
        ]
      },
      {
        "file": "/var/www/html/ocs/v1.php",
        "line": 43,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/ocsapp/apps/files/api/v1/templates/create"
        ]
      },
      {
        "file": "/var/www/html/ocs/v2.php",
        "line": 7,
        "args": [
          "/var/www/html/ocs/v1.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/html/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php",
    "Line": 113,
    "message": "Client error: `POST https://cloud.domain.de/cool/transform-document-structure` resulted in a `403 Forbidden` response",
    "exception": [],
    "CustomMessage": "Client error: `POST https://cloud.domain.de/cool/transform-document-structure` resulted in a `403 Forbidden` response"
  },
  "id": "675c5fecb6660"
``` 

</p>
</details> 

<details><summary>Details</summary>
<p>

```
{
  "reqId": "KwCoddSAVIKkefDPyhsN",
  "level": 3,
  "time": "2024-12-13T16:21:44+00:00",
  "remoteAddr": "IP",
  "user": "USER",
  "app": "richdocuments",
  "method": "POST",
  "url": "/ocs/v2.php/apps/files/api/v1/templates/create",
  "message": "Client error: `POST https://cloud.domain/cool/transform-document-structure` resulted in a `403 Forbidden` response",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "version": "30.0.4.1",
  "data": {
    "app": "richdocuments"
  },
  "id": "675c5fecb6667"
}
``` 

</p>
</details>
